version: '3.9'

services:

  service-a:
    build:
      context: ../
      dockerfile: setup/Dockerfile
    image: service-a
    container_name: service-a-api
    volumes:
      - ../:/app
    ports:
      - "8080:80"
      