version: '3.9'

services:

  service-a:
    build:
      context: ../
      dockerfile: setup/Dockerfile
    image: service-a
    container_name: service-a-api
    volumes:
      - ../:/app
    ports:
      - "8080:80"
    # depends_on:
    #   - db

  # db:
  #   image: mysql:8.0
  #   container_name: db-mysql
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: gm
  #     MYSQL_USER: gm
  #     MYSQL_PASSWORD: gm
      