version: '3.9'

services:

  service-b:
    build:
      context: ../
      dockerfile: setup/Dockerfile
    image: service-b
    container_name: service-b-api
    volumes:
      - ../:/app
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: microservices